@isTest
private class RestoTestUtility {

    static testmethod void DeleteRestaurant() {
	// Create an invoice statement with a line item then try to delete it
	//Restaurant__c resto = TestDataFactory.createRestaurant();
	//Test.startTest();
	//Database.DeleteResult result = Database.delete(inv, false);
	//Test.stopTest();
	// Verify invoice with a line item didn't get deleted.
	//System.assert(!result.isSuccess());
    }
}